# -*- coding: utf-8 -*-
"""Text Summarization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VGqYp-kuVmKWeM_lFYsKH6aGhedTQdCV
"""

!pip install bert-extractive-summarizer

!pip install  spacy 
!pip install  transformers
!pip install  neuralcoref

from summarizer import Summarizer
from pprint import pprint

with open("/content/drive/MyDrive/NLP/Train.story", 'r') as file:
    train_data = file.read().replace('\n', '')
train_data = train_data.replace("\ufeff", "")
train_data

model = Summarizer()

result_train = model(train_data, num_sentences=5, min_length=60)

full = ''.join(result_train)

pprint(full)

with open("/content/drive/MyDrive/NLP/Test.story", 'r') as file:
    test_data = file.read().replace('\n', '')
test_data = test_data.replace("\ufeff", "")
test_data

result_test = model(test_data, num_sentences=5, min_length=60)
summary_test = ''.join(result_test)
pprint(summary_test)

